### ISSUE TITLE
ツール名がない

### ISSUE THREAD

**Issue by kusumoto-lab** [ty-v1/kari2#72]
格好いい名前が欲しい

アナグラム or 再帰的頭字語が望ましい

**Comment by kusumoto-lab** [comment]
genProg
apr
visualization
tree
kGenProg
overview
process

**Comment by kusumoto-lab** [comment]
mac aws

# **Macaw(s)**: 
* A :apr
* C :comprehension 
* A :assist 
* W :With viSualization
(* S: service)

**Comment by ty-v1** [comment]
Macaw is an Apr Comprehension Assist tool With visualization
